# Generated by Django 3.0.12 on 2021-04-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('contactNumber', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fullName', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('aadharNumber', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('docId', models.AutoField(primary_key=True, serialize=False)),
                ('doctorName', models.CharField(max_length=255, unique=True)),
                ('hospitalName', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('fullName', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=20)),
                ('contactNumber', models.CharField(max_length=12)),
                ('aadharNumber', models.CharField(max_length=16)),
            ],
        ),
    ]
