# Generated by Django 3.0.7 on 2021-04-24 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicineId', models.AutoField(primary_key=True, serialize=False)),
                ('medicineName', models.CharField(max_length=255, unique=True)),
                ('schedule', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=13)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('billId', models.AutoField(primary_key=True, serialize=False)),
                ('medicines', models.CharField(max_length=1000)),
                ('billAmount', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='pharmacy_app.Customer')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='pharmacy_app.Doctor')),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='pharmacy_app.Pharmacist')),
            ],
        ),
    ]
