# Generated by Django 3.0.7 on 2021-04-24 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_app', '0002_billing_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='pharmacy_app.Doctor'),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='aadharNumber',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
